/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SaltedUniversalProfileFactory } from "./SaltedUniversalProfileFactory";
export * as factories from "./factories";
export { SaltedUniversalProfileFactory__factory } from "./factories/SaltedUniversalProfileFactory__factory";
